### ISSUE TITLE
[feature request] Multiple restore keys/fallback keys

### ISSUE THREAD

**Issue by davidwallacejackson** [nienbo/cache-buildkite-plugin#20]
Would it be possible to add support for multiple restore keys with priority order? I'm thinking about something along the lines of `restore-keys` in GitHub's cache Action: https://github.com/actions/cache/blob/main/examples.md#macos-and-ubuntu

So in the linked example, in the event of a cache miss on `${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}`, the runner will instead restore the newest cache with the prefix `${{ runner.os }}-node-`. It can help when you're iterating on new dependencies, but the really killer feature it enables is for incremental build caching: By backing up, say, `node_modules/.cache` with a key of `node-cache-${GIT_BRANCH}-${COMMIT_SHA}`, and then using `node-cache-${GIT_BRANCH}-` and then `node-cache-master-` as restore keys, you can make sure that:

* repeated builds get the same cache
* new commits on a feature branch get the cache of the most recent build on that branch
* new commits on a **new** feature branch get the cache from the most recent build of master, likely what they were forked from

For the filesystem-backed cache backends, I'd think this could be accomplished pretty easily by `ls`ing on a glob -- for S3 and the future Google Cloud backend, I'm pretty sure those bucket stores both have "list by prefix" APIs. If I were handier with Bash I'd just make a PR for it, but I figured I'd at least ask. Thanks for making this plugin available for all of us!

**Comment by gencer** [comment]
Hey @davidwallacejackson I believe this will be a good feature and doable. We should do both for `tarball` and `s3` backend. I'll working on it ASAP.

Personal note: I also think the same. Since my packages a bit larger, newest builds rebuild the packages every change and it takes around 5 minutes. If we do this it will take few seconds incrementally.

**Comment by davidwallacejackson** [comment]
Brilliant, thank you so much!

**Comment by gencer** [comment]
Hi @davidwallacejackson,

We have a working test on `restore-keys` branch which will evolve to `v2.4.0` soon. Here is a screenshot from my pipeline:

![image](https://user-images.githubusercontent.com/1711576/109522897-d375ff80-7abf-11eb-89b9-f213f40e1d56.png)

As you can see, first hit was direct and failed because I deleted it from S3 manually to test. Then it looked for `v1-cache-` prefix and found the cache.

Currently it finds 1 file per restore key and that file is the most up-to-date one on S3 by using `LastModified`. It uses `jq` to fetch the keys. On windows also there is a `jq` suppoprt which will also work on that platform too :)

There are 2 things remain for this:

1. Adding support for `{{ runner.os }}` on that key list
2. tarball support

P.S.: Sorry for the delay.

**Comment by gencer** [comment]
I've also added new cache key templates for:

- `{{ git.branch }}` which prints current build git branch
- `{{ git.commit }}` which prints current build git commit SHA

See updated README/CHANGELOG at `restore-keys` branch for all changes for `v2.4.0`

**Comment by gencer** [comment]
![109526412-957ada80-7ac3-11eb-9d15-3703bb160aac](https://user-images.githubusercontent.com/1711576/109546097-ca465c00-7ada-11eb-9543-5c46fed81944.png)


1. Direct cache hit tried.
2. Direct cache hit fails. Fallback to restore keys -if any-
3. First restore key tried. No luck. Fallback to other restore keys...
4. Second restore key tried.
5. Cache hit. We have a matched tarball for 2nd restore key.
6. Download matched tarball from s3
7. Bundler uses restored tarball.
8. Not in screenshot: New cache created and uploaded to s3. New build will use it either in first hit or by restore keys.

Please note that, if there are more than 1 tarball on disk or s3 that matches with restore key, only the most recent (LastModified) one will be used.
